"""add_analysis_run_history

Revision ID: 8e489b9aca1b
Revises: a1b2c3d4e5f6
Create Date: 2026-08-03 14:12:57.483663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e489b9aca1b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_run_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('url_or_filename', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('video_duration', sa.Float(), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('words_per_minute', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_run_history_date_time'), 'analysis_run_history', ['date_time'], unique=False)
    op.create_index('run_history_user_date_idx', 'analysis_run_history', ['user_id', 'date_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('run_history_user_date_idx', table_name='analysis_run_history')
    op.drop_index(op.f('ix_analysis_run_history_date_time'), table_name='analysis_run_history')
    op.drop_table('analysis_run_history')
    # ### end Alembic commands ###
