"""add_temporary_password_reset_fields

Revision ID: f7c7fd0ce13a
Revises: 6a7b89c01d2e
Create Date: 2026-07-22 09:02:16.829931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c7fd0ce13a'
down_revision: Union[str, Sequence[str], None] = '6a7b89c01d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_sqlite = conn.dialect.name == "sqlite"
    default_val = "0" if is_sqlite else "false"
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default=sa.text(default_val), nullable=False))
        batch_op.add_column(sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_reset_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temporary_password_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_users_password_reset_by', 'users', ['password_reset_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_password_reset_by', type_='foreignkey')
        batch_op.drop_column('temporary_password_expires_at')
        batch_op.drop_column('password_reset_by')
        batch_op.drop_column('password_reset_at')
        batch_op.drop_column('must_change_password')
    # ### end Alembic commands ###
